use training;

CREATE TABLE CUSTOMER_TBL(
cust_id INT,
cust_name VARCHAR(100),
city VARCHAR(100)
);


INSERT INTO CUSTOMER_TBL VALUES(1000,'Bala','Chennai');
INSERT INTO CUSTOMER_TBL VALUES(1001,'Malini','Bangalore');
INSERT INTO CUSTOMER_TBL VALUES(1002,'Ashwin','Hyderabad');
INSERT INTO CUSTOMER_TBL VALUES(1003,'Pankaj','Pune');
INSERT INTO CUSTOMER_TBL VALUES(1004,'Yogesh','Delhi');

CREATE TABLE TRANSACTION_TBL(
trans_id INT,
cust_id INT,
product_name VARCHAR(100),
amount INT
);


INSERT INTO TRANSACTION_TBL VALUES(1,1000,'TV',70000);
INSERT INTO TRANSACTION_TBL VALUES(2,1001,'Laptop',75000);
INSERT INTO TRANSACTION_TBL VALUES(3,1001,'Charger',12000);
INSERT INTO TRANSACTION_TBL VALUES(4,1002,'Fridge',36000);
INSERT INTO TRANSACTION_TBL VALUES(5,1000,'Mobile',30000);
INSERT INTO TRANSACTION_TBL VALUES(6,1002,'Chocalate',10000);
INSERT INTO TRANSACTION_TBL VALUES(7,1003,'Desktop',55000);
INSERT INTO TRANSACTION_TBL VALUES(8,1003,'Watch',20000);
INSERT INTO TRANSACTION_TBL VALUES(9,1003,'Microoven',33000);
INSERT INTO TRANSACTION_TBL VALUES(10,1005,'TV',70000);


-- INNER JOIN 

SELECT * FROM customer_tbl c INNER JOIN transaction_tbl t ON c.cust_id = t.cust_id;
SELECT * FROM customer_tbl c JOIN transaction_tbl t ON c.cust_id = t.cust_id;

-- LEFT OUTER JOIN
SELECT * FROM CUSTOMER_TBL c LEFT OUTER JOIN TRANSACTION_TBL t ON c.cust_id=t.cust_id;
SELECT * FROM CUSTOMER_TBL c LEFT JOIN TRANSACTION_TBL t ON c.cust_id=t.cust_id;


-- RIGHT OUTER JOIN
SELECT * FROM CUSTOMER_TBL c RIGHT OUTER JOIN TRANSACTION_TBL t ON c.cust_id=t.cust_id;
SELECT * FROM CUSTOMER_TBL c RIGHT  JOIN TRANSACTION_TBL t ON c.cust_id=t.cust_id;

-- FULL OUTER JOIN
SELECT * FROM CUSTOMER_TBL c JOIN TRANSACTION_TBL t;

-- SELF JOIN

CREATE TABLE EMPLOYEE_TBL(
emp_id INT,
emp_name VARCHAR(100),
salary INT,
mgr_id INT
);

INSERT INTO EMPLOYEE_TBL VALUES(1000,'Ashwin',20000,1002);
INSERT INTO EMPLOYEE_TBL VALUES(1001,'Arun',30000,1002);
INSERT INTO EMPLOYEE_TBL VALUES(1002,'Vicky',25000,1005);
INSERT INTO EMPLOYEE_TBL VALUES(1003,'Divya',30000,1005);
INSERT INTO EMPLOYEE_TBL VALUES(1004,'Ranjitha',40000,1005);
INSERT INTO EMPLOYEE_TBL VALUES(1005,'Rajesh',35000,1000);

SELECT * FROM EMPLOYEE_TBL;

SELECT e1.emp_name , e1.salary, e2.emp_name as "mgr_name", e2.salary as "mgr_sal" 
FROM employee_tbl e1 JOIN  employee_tbl e2 
ON e1.mgr_id=e2.emp_id 
WHERE e1.salary > e2.salary;


SELECT e1.emp_name as "employee_name", e1.salary as "employee_salary",e2.emp_name as  "manager_name", e2.salary as "manager_salary"
FROM employee_tbl e1 JOIN employee_tbl e2
ON e1.mgr_id=e2.emp_id
WHERE e1.salary > e2.salary
